version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: aws/scripts/build_app
      timeout: 10000
      runas: root
  ApplicationStart:
    - location: aws/scripts/run_app
      timeout: 300
      runas: root